test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -231,9 +231,11 @@ runs:
         GEMINI_CLI_VERSION: '${{ inputs.gemini_cli_version }}'
         EXTENSIONS: '${{ inputs.extensions }}'
         USE_PNPM: '${{ inputs.use_pnpm }}'
+        GEMINI_API_KEY: '${{ inputs.gemini_api_key }}'
+
       shell: 'bash'
       run: |-
-        set -euo pipefail
+        set -exuo pipefail
 
         VERSION_INPUT="${GEMINI_CLI_VERSION:-latest}"
 
@@ -252,6 +254,7 @@ runs:
           npm install
           npm run bundle
           npm install --silent --no-audit --prefer-offline --global .
+          gemini -p "hiiii partha"
         fi
         echo "Verifying installation:"
         if command -v gemini >/dev/null 2>&1; then
@@ -275,7 +278,7 @@ runs:
       id: 'gemini_run'
       shell: 'bash'
       run: |-
-        set -euo pipefail
+        set -exuo pipefail
 
         # Create a temporary directory for storing the output, and ensure it's
         # cleaned up later
@@ -286,17 +289,17 @@ runs:
         }
         trap cleanup EXIT
 
-        # Keep track of whether we've failed
+        # Keep track of whether we've failed 
         FAILED=false
-
+        gemini -d -p "hiiii partha 2"
         # Run Gemini CLI with the provided prompt, streaming responses in debug
         if [[ "${DEBUG}" = true ]]; then
           echo "::warning::Gemini CLI debug logging is enabled. This will stream responses, which could reveal sensitive information if processed with untrusted inputs."
-          if ! { gemini --yolo --prompt "${PROMPT}" 2> >(tee "${TEMP_STDERR}" >&2) | tee "${TEMP_STDOUT}"; }; then
+          if !  gemini -d --yolo --prompt "${PROMPT}" ; then
             FAILED=true
           fi
         else
-          if ! gemini --yolo --prompt "${PROMPT}" 2> "${TEMP_STDERR}" 1> "${TEMP_STDOUT}"; then
+          if ! gemini -d --yolo --prompt "${PROMPT}"; then
             FAILED=true
           fi
         fi
